### ISSUE TITLE
Ingredient problems

### ISSUE THREAD

**Issue by timarney** [iancanderson/ingreedy-js#5]
In the case of something like - 
**"Crushed red pepper _flakes"_**
the parser throws an error as no amount is given.

Also I submitted a pull request for the word 'dozen' but I found an additional issue.  In the case of 
**_"2 dozen (7-8 inch) egg roll wrappers"_**
I believe the parser is looking for a container

**Comment by Adeering** [comment]
I have the same issue, did you find a solution for this as I would really like to use this parser and not have to make my own from scratch

**Comment by timarney** [comment]
I didn't - I started digging into the generator for the parser (this one I think http://pegjs.org/) but I didn't get very far with it.

**Comment by Adeering** [comment]
yeah me neither, right now Im basically doing a quick gsub of the string to see if there is any numbers in it.  If there arent any numbers I just assign the whole string to ingredient and leave amount and unit blank.  If there is a number I use the parser and so far it seems to work for every test Ive put it through.  Not the greatest solution but if it works
